default: &default
  adapter: sqlserver
  # encoding: utf8mb4
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['CHESS_SQL_DB_NAME'] %>
  host: <%= ENV['CHESS_SQL_HOST'] %>
  port: <%= ENV['CHESS_SQL_PORT'] %>
  username: <%= ENV['CHESS_SQL_USERNAME'] %>
  password: <%= ENV['CHESS_SQL_PASSWORD'] %>
  azure: <%= ENV['CHESS_SQL_AZURE'] == 'true' %>

test:
  <<: *default
  database: <%= ENV['CHESS_SQL_DB_NAME'] %>
  host: <%= ENV['CHESS_SQL_HOST'] %>
  port: <%= ENV['CHESS_SQL_PORT'] %>
  username: <%= ENV['CHESS_SQL_USERNAME'] %>
  password: <%= ENV['CHESS_SQL_PASSWORD'] %>
  azure: <%= ENV['CHESS_SQL_AZURE'] == 'true' %>
